### ISSUE TITLE
browser-sync not found

### ISSUE THREAD

**Issue by rowboat85** [alexciarlillo/react-wp#2]
Hi I am currently getting an error upon gulp build. I have removed the 'proxy' line of code as well

module.js:338
    throw err;
          ^
Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\xampp\htdocs\wordpress\wp-content\themes\react-wp\
gulp\tasks\browserify.js:10:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by alexciarlillo** [comment]
I have added browser-sync as a dev dependency in packages.json. I usually have it globally installed from npm.

https://github.com/alexciarlillo/react-wp/commit/3232c0cc6d3e2d2beec50ff1cd907e6754af876c
